[project]
name = "libreglisse"
version = "0.1.0-a.5.z"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/Wmbat/libreglisse/tree/master/"

[pages]
homepage = "docs/homepage.md"

[paths]
compile_commands = "compile_commands.json"
output_dir = "hdoc-output"
