name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest Clang", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Download Packages
      if: ${{ matrix.config.cc == 'gcc' && matrix.config.cxx == 'g++' }}
      run: sudo apt update && sudo apt-get install gcc-10 g++-10
      if: ${{ matrix.config.cc == 'clang' && matrix.config.cxx == 'clang++' }}
      run: sudo apt update && sudo apt-get install clang-10
    - name: Configure
      if: ${{ matrix.config.cc == 'gcc' && matrix.config.cxx == 'g++' }}
      run: cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DMONADS_BUILD_TESTS=ON ./
    - name: Build
      run: make
