name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Download Packages
      run: | 
        sudo apt update
        sudo apt-get install gcc-10 g++-10
    - name: Configure
      run: cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_BUILD_TYPE=Debug -DMONADS_BUILD_TESTS=ON ./
    - name: Build
      run: make
    - name: Run unit tests
      run: cd out/gcc/debug/monads && ./monads_test
