name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest Clang",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Download GCC
      if: ${{ matrix.config.cc == 'gcc' && matrix.config.cxx == 'g++' }}
      run: sudo apt update && sudo apt-get install gcc-10 g++-10
    - name: Download Clang
      if: ${{ matrix.config.cc == 'clang' && matrix.config.cxx == 'clang++' }}
      run: sudo apt update && sudo apt-get install clang-10
    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${ { matrix.config.cc } })
        set(ENV{CXX} ${ { matrix.config.cxx } })

        execute_process(
          COMMAND ${ { steps.cmake_and_ninja.outputs.cmake_dir } }/cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${ { matrix.config.build_type } }
            -D MONADS_BUILD_TESTS=ON
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Build
      run: make
