name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest Clang",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Download GCC
      if: ${{ matrix.config.cc == 'gcc' && matrix.config.cxx == 'g++' }}
      run: sudo apt update && sudo apt-get install gcc-10 g++-10
    - name: Download Clang
      if: ${{ matrix.config.cc == 'clang' && matrix.config.cxx == 'clang++' }}
      run: sudo apt update && sudo apt-get install clang-10 gcc-10 g++-10
    - name: Configure
      shell: cmake -P {0}
      run: |
        set(C_COMPILER ${{ matrix.config.cc }})
        set(CXX_COMPILER ${{ matrix.config.cxx }})

        if (C_COMPILER STREQUAL "gcc" AND CXX_COMPILER STREQUAL "g++")
          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D CMAKE_C_COMPILER=/usr/bin/gcc-10
              -D CMAKE_CXX_COMPILER=/usr/bin/g++-10
              -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
              -D MONADS_BUILD_TESTS=ON
            RESULT_VARIABLE result
          )
        else ()
          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D CMAKE_C_COMPILER=/usr/bin/clang-10
              -D CMAKE_CXX_COMPILER=/usr/bin/clang++-10
              -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
              -D MONADS_BUILD_TESTS=ON
            RESULT_VARIABLE result
          )
        endif()

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Build
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake --build build
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

