name: Documentation

on: [push]
#on:
  #  push:
  #    tags:
  #      - "*"

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install wget gnupg
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo bash -c "echo \"deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" >> /etc/apt/sources.list.d/llvm.list"
          sudo bash -c "echo \"deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" | sudo tee -a /etc/apt/sources.list.d/llvm.list"
          sudo apt-get -y update
          sudo apt-get -y install \
              build-essential \
              meson \
              ninja-build \
              cmake \
              xxd \
              clang-12 \
              libclang-common-12-dev \
              libclang-12-dev \
              lld-12 \
              groff \
              unzip \
              pkg-config \
              git \
              zlib1g-dev \
              libssl-dev \
              libcurl4-openssl-dev
         
      - name: Get hdoc 
        run: |
          git clone https://github.com/hdoc/hdoc
          cd hdoc
          sudo meson build && sudo ninja -C build

#      - name: Publish
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs/html
#
