name: Documentation

on: [push]
#on:
  #  push:
  #    tags:
  #      - "*"

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get remove llvm-11 llvm-10
          sudo apt-get remove clang-11 clang-10
          sudo apt-get -y update
          sudo apt-get -y install wget gnupg curl
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo bash -c "echo \"deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" >> /etc/apt/sources.list.d/llvm.list"
          sudo bash -c "echo \"deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" >> /etc/apt/sources.list.d/llvm.list"
          sudo apt-get -y update
          sudo apt-get -y install \
              build-essential \
              meson \
              ninja-build \
              cmake \
              xxd \
              clang-12 \
              libclang-common-12-dev \
              libclang-12-dev \
              lld-12 \
              groff \
              unzip \
              pkg-config \
              git \
              zlib1g-dev \
              libssl-dev \
              libcurl4-openssl-dev

      - name: Get Build2 
        run: |
          cd ../ && mkdir build2-build && cd build2-build
          curl -sSfO https://download.build2.org/0.13.0/build2-install-0.13.0.sh
          shasum -a 256 -b build2-install-0.13.0.sh
          sh build2-install-0.13.0.sh
          cd ../

      - name: Get hdoc 
        run: |
          git clone https://github.com/hdoc/hdoc
          cd hdoc
          sudo meson build && sudo ninja -C build
          cd ../libreglisse/
          hdoc/build/hdoc --verbose
          ls -lah

#      - name: Publish
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs/html
#
