name: Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest Clang",
            os: ubuntu-latest,
            cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Download GCC
      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
      run: sudo apt-get install gcc-10 g++-10
    - name: Download Clang
      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
      run: sudo apt-get install clang-10 gcc-10 g++-10
    - name: Configure
      shell: cmake -P {0}
      run: |
        set(C_COMPILER ${{ matrix.config.cc }})
        set(CXX_COMPILER ${{ matrix.config.cxx }})

        if (C_COMPILER STREQUAL "gcc" AND CXX_COMPILER STREQUAL "g++")
          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D CMAKE_C_COMPILER=/usr/bin/gcc-10
              -D CMAKE_CXX_COMPILER=/usr/bin/g++-10
              -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE}
              -D BUILD_TESTS=ON
            RESULT_VARIABLE result
          )
        else ()
          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D CMAKE_C_COMPILER=/usr/bin/clang-10
              -D CMAKE_CXX_COMPILER=/usr/bin/clang++-10
              -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE}
              -D BUILD_TESTS=ON
            RESULT_VARIABLE result
          )
        endif()

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Build
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake --build build
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        execute_process(
          COMMAND ctest --verbose -j ${n}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Upload coverage to Codecov
      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
      uses: codecov/codecov-action@v1   
      with:
        files: ./build/tests/CMakeFiles/monads_test.dir/monads/main.cpp.gcno,./build/tests/CMakeFiles/monads_test.dir/monads/main.cpp.gcda
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.gz
